eoscan_app/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf.urls.static import static
from django.conf import settings

import debug_toolbar
import captcha

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recognition.urls', namespace='recognition')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.THUMBNAIL_MEDIA_URL,
                          document_root=settings.THUMBNAIL_MEDIA_ROOT)

recognition/urls.py
from django.urls import path
from .views import index_view, personal_view, task_status_view, \
    ToolListView, ContactFormView, ToolDetailView, about_view, \
    order_list_view, OrderDetailView, OrderCreateView, OrderUpdateView, \
    UserCreateView, LoginUserView, LogoutUserView, OrderDeleteView, \
    reports_view, ToolTypeListView, OrderDownloadView

app_name = 'recognition'

urlpatterns = [
    path('', index_view, name='index'),
    path('task_status/', task_status_view, name='task_status'),
    # path('personal/<int:pk>/', personal_view, name='personal'),
    path('personal/', personal_view, name='personal'),
    path('reports/', reports_view, name='reports'),
    path('tool_list/<int:pk>/', ToolDetailView.as_view(), name='tool_info'),
    path('tool_list/', ToolListView.as_view(), name='tool_list'),
    path('tooltype_list/', ToolTypeListView.as_view(), name='tooltype_list'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('about/', about_view, name='about'),
    path('order_list/<int:pk>/order_update/', OrderUpdateView.as_view(),
         name='order_update'),
    path('order_list/<int:pk>/order_delete/', OrderDeleteView.as_view(),
         name='order_delete'),
    path('order_list/<int:pk>/order_download/', OrderDownloadView.as_view(),
         name='order_download'),
    path('order_list/<int:pk>/', OrderDetailView.as_view(),
         name='order_detail'),
    path('order_list/', order_list_view, name='order_list'),
    path('order_create/', OrderCreateView.as_view(), name='order_create'),
    path('registry/', UserCreateView.as_view(), name='registry'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
]

recognition/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from captcha.fields import CaptchaField
from django.core import validators
from .tasks import send_mail_task
from .models import Tool, Order, AdvUser


# класс форм, не связанных с моделью
class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.
                             TextInput(attrs={'class': 'form-control'}))
    subject = forms.CharField(widget=forms.
                              TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.
                              Textarea(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='Input text',
                           error_messages={'invalid': 'wrong text'})

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        text = form.cleaned_data['message']
        email = form.cleaned_data['email']
        send_mail_task.delay(subject, text, email)
        return super().form_valid(form)


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your password',
    }))

    class Meta:
        model = AdvUser
        # fields = '__all__'
        fields = ('username', 'first_name', 'last_name', 'email',
                  'password1', 'password2')
        widgets = {'username': forms.TextInput(attrs={
            'placeholder': 'John Gault',
            'class': 'col-md-12form-control'}),
                   'email': forms.EmailInput(attrs={
                       'placeholder': 'your@mail.com',
                       'class': 'col-md-12form-control'}),
                   }


class LoginForm(AuthenticationForm):
    class Meta:
        fields = '__all__'


class ToolForm(forms.ModelForm):
    class Meta:
        model = Tool
        exclude = ('avatar', )


class OrderForm(forms.ModelForm):

    tool = forms.ModelChoiceField(queryset=Tool.objects.all(),
                                  widget=forms.widgets.RadioSelect(),
                                  empty_label=None)
    img = forms.ImageField(validators=[validators.FileExtensionValidator(
        allowed_extensions=('gif', 'png', 'jpg', 'jpeg', 'tif', 'tiff')
    )],
    error_messages={'invalid_extension': 'not supported format'})

    captcha = CaptchaField(label='Input text',
                           error_messages={'invalid': 'wrong text'})

    class Meta:
        model = Order
        exclude = ('user', 'size', 'height', 'width', 'extension',
                   'path', 'string_geodata', 'created', 'discount', 'source_path',
                   'result_folder_path', 'result_path', 'start_datetime',
                   'finish_datetime','task_id',
                   'task_status', 'priority', 'description')
        widgets = {
            'inputed_geodata': forms.widgets.Textarea(attrs={
                'class': 'form-control',
                'cols': 50,
                'rows': 5,
            }),
        }

recognition/views.py
import time
import os
from django.shortcuts import render, redirect
from .models import AdvUser, Order, Tool, ToolType
from .tasks import save_orders, send_mail_task, tool_1_task
from celery import current_app, result, Celery
from django.views.generic import ListView, DetailView, UpdateView, \
    CreateView, FormView, DeleteView
from .forms import ContactForm, OrderForm, RegistrationForm, LoginForm
from eoscan_app.settings import BYTES_TO_MB_COEF, BASE_DIR

from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
# from django.contrib import messages
from django.urls import reverse_lazy
from captcha.fields import CaptchaField
from django.http import FileResponse
from django.core.paginator import Paginator
import random
# from osgeo import gdal
# import cv2
# import numpy as np
# from scipy import ndimage
# import glob
# from matplotlib import pyplot as plt


# PERMISSIONS ________________________________________________


class AdminOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        # просто сформулировать условие выдачи прав
        # return self.request.user.email.endswith('@example.com')
        return self.request.user.is_superuser


class StaffOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

# CONTACTS ________________________________________________


class ContactFormView(LoginRequiredMixin, FormView):
    template_name = "recognition/contact.html"
    form_class = ContactForm
    success_url = '/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Contact'
        return context

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        text = form.cleaned_data['message']
        email = form.cleaned_data['email']
        send_mail_task.delay(subject, text, email)
        return super().form_valid(form)


# ABOUT ________________________________________________

def about_view(request):
    text = """eoScan is the collection of tools for recognizing 
    images in agriculture and other industries."""
    context = {'text': text, 'active_page': 'About'}
    return render(request, 'recognition/about.html', context)


# USER ________________________________________________


class UserCreateView(CreateView):
    model = AdvUser
    form_class = RegistrationForm
    success_url = '/'
    template_name = 'recognition/register.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Register'
        return context


class LoginUserView(LoginView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'recognition/login.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Login'
        return context


class LogoutUserView(LogoutView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Logout'
        return context


# TOOLS ________________________________________________


class ToolListView(ListView):
    model = Tool
    template_name = "recognition/tool_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Tools'
        return context


class ToolDetailView(DetailView):
    model = Tool
    template_name = "recognition/tool_info.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Tools'
        return context

# TOOLTYPE ________________________________________________


class ToolTypeListView(ListView):
    model = ToolType
    template_name = "recognition/tooltype_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Tool types'
        return context

# ORDER ________________________________________________


# class OrderListView(LoginRequiredMixin, ListView):
#     model = Order
#     template_name = "recognition/order_list.html"
#
#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(*args, **kwargs)
#
#         context['active_page'] = 'Orders'
#         return context

@login_required
def order_list_view(request):
    context = {}
    object_list = Order.objects.order_by('-created').\
        select_related('tool', 'tool__tool_type').\
        filter(user__pk=request.user.id)
    context['active_page'] = 'Orders'

    paginator = Paginator(object_list, 10)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context['page'] = page
    context['object_list'] = page.object_list

    user_id = request.user.id
    if request.method == 'POST':
        task = save_orders.delay(user_id=user_id)
        context['task_id'] = task.id

        while current_app.AsyncResult(task.id).status != 'SUCCESS':
            print(current_app.AsyncResult(task.id).status)
            time.sleep(1)
            continue

        filename = f'media/reports/orders_user_{user_id}.txt'
        file = FileResponse(open(filename, 'rb'), as_attachment=True)
        return file

    return render(request, 'recognition/order_list.html', context)


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "recognition/order_detail.html"

    # def get_object(self):
    #     return get_object_or_404(User, id=self.request.user.first_name)
    # user = get_object()
    # extra_context = {'user': user}

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Orders'

        return context

    def post(self, request, *args, **kwargs):

        req = self.request.__dict__['META']['HTTP_REFERER']
        req = int(req.split('order_list/')[-1].split('/')[0])
        task = tool_1_task.delay(order_id=req)
        order = Order.objects.get(pk=req)
        order.task_id = str(task.id)
        print('TASK ID! ', task.id)
        order.save()

        return redirect('recognition:order_detail', req)

# def download_view(request, order_id):
#     context = {}
#     context['order_id'] = order_id
#     if request.method == 'POST':
#         filename = os.path.join(BASE_DIR, 'media', str(Order.objects.get(pk=req).img))
#         file = FileResponse(open(filename, 'rb'), as_attachment=True)
#         return file


class OrderDownloadView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "recognition/order_download.html"
    # success_url = '/order_list/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Orders'
        return context

    def post(self, request, *args, **kwargs):

        req = self.request.__dict__['META']['HTTP_REFERER']
        req = int(req.split('order_list/')[-1].split('/')[0])
        order = Order.objects.get(pk=req)
        try:
            filename = order.result_path
            file = FileResponse(open(filename, 'rb'), as_attachment=True)
        except:
            user_id = self.request.user.id
            result_folder_path = order.result_folder_path
            extension = order.extension
            filenames = [i.name for i in os.scandir(result_folder_path) if
                         i.is_file() and f'{req}.{user_id}.{extension}'
                         in i.name]
            filename = os.path.join(
                result_folder_path, random.choice(filenames)
            )
            file = FileResponse(open(filename, 'rb'), as_attachment=True)
            order.result_path = filename
            order.save()

        return file


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    template_name = "recognition/order_create.html"
    form_class = OrderForm
    success_url = "/order_list/"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active_page'] = 'Orders'
        return context

    def form_valid(self, form):
        user_id = self.request.user.id
        user = AdvUser.objects.get(id=user_id)
        form.instance.user = user
        order = form.save(commit=False)
        order.save()
        return super().form_valid(form)


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    template_name = 'recognition/order_create.html'

    form_class = OrderForm

    def form_valid(self, form):
        try:
            req = self.request.__dict__['META']['HTTP_REFERER']
            req = int(req.split('order_list/')[-1].split('/')[0])
            self.success_url = f'/order_list/{req}/'
        except:
            self.success_url = '/order_list/'
        return super().form_valid(form)


class OrderDeleteView(DeleteView):
    model = Order
    template_name = 'recognition/order_delete.html'
    success_url = '/'

# INDEX ________________________________________________


def index_view(request):
    context = {}
    context['text'] = "You can start!"
    return render(request, 'recognition/index.html', context)


@login_required
def reports_view(request):
    user_id = request.user.id
    context = {"active_page": "Reports"}
    if request.method == 'POST':
        task = save_orders.delay(user_id=user_id)
        context['task_id'] = task.id
    return render(request, 'recognition/reports.html', context)


@login_required
def personal_view(request):

recognition/templates/recognition/about.html
{% extends "base.html" %}

{% block title %}
    About
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> About the Project </h3>
</div>

<div class="container-fluid">
    {{text}}
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

recognition/templates/recognition/contact.html
{% extends "base.html" %}

{% block title %}
    Contact
{% endblock %}

{% block main %}

<br>
<div class="alert alert-info" role="alert">
    <h3> Contact us </h3>
</div>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Send</button>
</form>
{% endblock %}

recognition/templates/recognition/index.html
{% extends "base.html" %}


{% block title %}
Main
{% endblock %}

{% block main %}

<br>
<div class="container-fluid">
    {% if user.first_name %}
    <p class="text-left"><i>Hello, {{user.first_name}} {{user.last_name}}</i>!</p>
    {% else %}
    <p class="text-left"><i>Hello!</i></p>
    {% endif %}
</div>
<br>

<div class="container-fluid">
  <p class="figa"><img class="img-center" width="500px"
          src="./../../static/static_images/logo_alpha.png"
          alt="eoScan"></p>
</div>
<br>
<hr>
<br>

  <div class="container marketing">

    <div class="row">
      <div class="col-lg-4">
        <img class="img rounded-circle" width="140" height="140" src="./../../static/static_images/kuku.jpeg"><title>Placeholder</title>

        <h4>The definition of quality for germination of crops</h4>
        <p>A set of tools for recognizing anomalies in the development
          of agricultural crops, damage from pests, etc.
        </p>
        <p><a class="btn btn-secondary" href="{% url 'recognition:tooltype_list' %}#level-1" role="button">More details &raquo;</a></p>
      </div>
      <div class="col-lg-4">
        <img class="img rounded-circle" width="140" height="140" src="./../../static/static_images/kust.png"><title>Placeholder</title>

        <h4>Determination of areas occupied by agricultural crops</h4>
        <p>Determine the areas occupied by agricultural crops and the areas occupied by shrubs and forests.</p>
        <p><a class="btn btn-secondary" href="{% url 'recognition:tooltype_list' %}#level-2" role="button">More details &raquo;</a></p>
      </div>
      <div class="col-lg-4">
        <img class="img rounded-circle" width="140" height="140" src="./../../static/static_images/vshod.png"><title>Placeholder</title>

        <h4>The determination of the distances between the sprouts</h4>
        <p>Find deviations from technological distances, omissions, and doubles. Find out the proportion of plants outside the rows.
        </p>
        <p><a class="btn btn-secondary" href="{% url 'recognition:tooltype_list' %}#level-3" role="button">More details &raquo;</a></p>
      </div>
    </div>

{% endblock %}

recognition/templates/recognition/login.html
{% extends "base.html" %}

{% block title %}
    Log in
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> Log in </h3>
</div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Log in</button>
    </form>
{% endblock %}

recognition/templates/recognition/order_create.html
{% extends "base.html" %}


{% block title %}
New Order
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> New order </h3>
</div>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Create Order</button>
</form>

{% endblock %}

recognition/templates/recognition/order_detail.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}
Order {{object.id}}
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> Order # {{object.pk}}</h3>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm">
        <h3 class="figa">Image: </h3>
        <p class="figa">
            <img width="500px" src="{% thumbnail object.img 'default' %}">
        </p>
    </div>
    <div class="col-sm">
        <h3 class="figa">Data: </h3>
        <table class="table table-primary">
          <thead>
            <th scope="col">Feature</th>
            <th scope="col">Value</th>
          </thead>
          <tbody>
            <tr class="table-active">
                    <th scope="row">id</th>
                    <td>{{object.pk}}</td>
            </tr>
            <tr class="table">
                <th scope="row">Shape</th>
                <td>{{object.width}} x {{object.height}}</td>
            </tr>
                <tr class="table-active">
                <th scope="row">Size</th>
                <td>{{object.size|filesizeformat}}</td>
            </tr>
                <tr class="table">
                <th scope="row">File name</th>
                <td>{{object.img.name}}</td>
            </tr>
                <tr class="table-active">
                <th scope="row">Tool</th>
                <td>{{object.tool}}</td>
            </tr>
                <tr class="table">
                <th scope="row">Created</th>
                <td>{{object.created}}</td>
            </tr>
            </tr>
                <tr class="table-active">
                <th scope="row">Extension</th>
                <td>{{object.extension}}</td>
            </tr>
            </tr>
                <tr class="table">
                <th scope="row">Task id</th>
                <td>{{object.task_id}}</td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
</div>


<br>
<hr>
{% if object.task_id %}
<br>
<br>
<a href="{% url 'recognition:order_download' object.id %}">
    Download result
</a>
{% else %}
<br>
<br>
<a class="btn btn-primary" href="{% url 'recognition:order_update' object.id %}">
    Update
</a>

<br>
<br>
<form method="post" action="{% url 'recognition:order_detail' object.id %}">
{% csrf_token %}
<button type="submit" class="btn btn-primary">Process</button>
</form>

<br>
<a class="btn btn-danger" href="{% url 'recognition:order_delete' object.id %}">
    Delete
</a>
{% endif %}


{% endblock %}

recognition/templates/recognition/order_list.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}
Orders
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3>My orders</h3>
</div>

<a class="btn btn-primary" href="{% url 'recognition:order_create' %}">
    Create new
</a>

<br>
<br>

<div class="container-fluid">

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Tool</th>
            <th scope="col">Status</th>
            <th scope="col">Process geodata</th>
            <th scope="col">Image</th>
            <th scope="col">Price</th>
            <th scope="col">Created</th>
            <th scope="col">Info</th>

        </tr>
        </thead>
        <tbody>
        {% for order in object_list %}
        <tr>
            <th scope="row">{{ order.id }}</th>
            <td>{{order.tool.name}}</td>
            <td>{{order.task_status}}</td>
            <td>{{order.tool.tool_type.proc_geodata}}</td>
            {% if order.img %}
            <td><img width="50px" height="50px" src="{% thumbnail order.img 'default' %}"></td>
            {% else %}
            <td> --- </td>
            {% endif %}
            <td>{{order.tool.price}}</td>
            <td>{{order.created}}</td>

            <td>
                    <a href="{% url 'recognition:order_detail' order.id %}">extra</a>
            </td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
</div>

<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">&lt</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    {% endif %}
    Part {{ page.number }} from {{ page.paginator.num_pages }}
    {% if page.has_next %}
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="?page={{ page.next_page_number }}">&gt</a>
    {% endif %}
</div>


<hr>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Download report</button>
</form>


{% endblock %}

recognition/templates/recognition/personal.html
{% extends "base.html" %}


{% block title %}
Personal
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> My data</h3>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Order</th>
<!--      <th scope="col">Image</th>-->
      <th scope="col">Status</th>
      <th scope="col">Process</th>
    </tr>
  </thead>
  <tbody>
  {% for order in orders %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>id {{order.pk}}</td>
      <td>{{order.task_id}} {{order.task_status}}</td>
      <td>
          <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Proc</button></form>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<!--<hr>-->
<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--    <button type="submit" class="btn btn-primary">Send mail</button>-->
<!--</form>-->

<!--<br>-->
<!--{% if task_id %}-->
<!--Отследить задачу <a href="/task_status/?task_id={{task_id}}">{{task_id}}</a>-->
<!--{% endif %}-->

<!--{% for image in images %}-->
<!--<li>{{image.pk}} {{image.img}}-->
<!--    <img width="50px" height="50px" src="{{ image.img.url }}">-->
<!--</li>-->
<!--{% endfor %}-->

{% endblock %}

recognition/templates/recognition/register.html
{% extends "base.html" %}

{% block title %}
    Registry
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3>Registration</h3>
</div>
    <form method="post">
        {% csrf_token %}
<!--        {{form.as_ul}}-->
<!--        {{form.as_table}}-->
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Log up</button>
    </form>
{% endblock %}

recognition/templates/recognition/reports.html
{% extends "base.html" %}


{% block title %}
Reports
{% endblock %}

{% block main %}

<br>
<div class="alert alert-info" role="alert">
    <h3> Download reports</h3>
</div>

<hr>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Save and send</button>
</form>

{% endblock %}<br>

recognition/templates/recognition/task_status.html
{% extends "base.html" %}


{% block title %}
Personal
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> Task status </h3>
</div>
<br>
Task id: {{task_id}}
<br>
Status: {{status}}

{% endblock %}

recognition/templates/recognition/tool_info.html
{% extends "base.html" %}


{% block title %}
Tool {{object.id}}
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> Tool #{{object.pk}} </h3>
</div>

<br>
<li>id: {{object.pk}} | type: {{object.tool_type.name}} |
    name: {{object.name}}</li>


{% endblock %}

recognition/templates/recognition/tool_list.html
{% extends "base.html" %}

{% block title %}
Tools
{% endblock %}

{% block main %}

<br>
<div class="alert alert-info" role="alert">
    <h1> Recognition models </h1>
</div>

<div class="container-fluid">

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Tool name</th>
            <th scope="col">Type</th>
            <th scope="col">Process geodata</th>
            <th scope="col">Price</th>
            <th scope="col">Created</th>
            <th scope="col">Description</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <th scope="row">{{ object.id }}</th>
            <td>{{object.name}}</td>
            <td>{{object.tool_type.name}}</td>
            <td>{{object.tool_type.proc_geodata}}</td>
            <td>{{object.price}}</td>
            <td>{{object.created}}</td>
            <td><a href="{% url 'recognition:tool_info' object.id %}">extra</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<br>
<br>
<br>
<br>
<br>

{% endblock %}

recognition/templates/recognition/tooltype_list.html
{% extends "base.html" %}


{% block title %}
ToolTypes
{% endblock %}

{% block main %}
<br>
<div class="alert alert-info" role="alert">
    <h3> Tool types </h3>
</div>

    <hr class="featurette-divider" id="level-1">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-Заголовок">The definition of quality for germination of crops. <span class="text-muted">Simple!</span></h2>
        <p class="lead">A set of tools for recognizing anomalies in the development
          of agricultural crops, damage from pests, etc.</p>
      </div>
      <div class="col-md-5">
        <img class="img-center" width="500" height="500"
             src="./../../static/static_images/landscape.jpg"
             alt="eoScan">
      </div>
    </div>

    <hr class="featurette-divider" id="level-2">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-Заголовок">Determination of areas occupied by agricultural crops. <span class="text-muted">Fast!</span></h2>
        <p class="lead">Determine the areas occupied by agricultural crops and the areas occupied by shrubs and forests.</p>
      </div>
      <div class="col-md-5 order-md-1">
<!--        <img class="img-center" width="500" height="500" src="./../../static/static_images/arable.jpg" alt="eoScan">-->
        <img class="img-center" width="500" height="500"
             src="./../../static/static_images/gif(3).gif"
             alt="eoScan">
      </div>
    </div>

    <hr class="featurette-divider" id="level-3">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-Заголовок">
            The determination of the distances between the sprouts.
            <span class="text-muted">Smart.</span>
        </h2>
        <p class="lead">
            Find deviations from technological distances, omissions, and doubles.
            Find out the proportion of plants outside the rows.
        </p>
      </div>
      <div class="col-md-5">
        <img class="img-center" width="500" height="500"
             src="./../../static/static_images/john-deere.jpg"
             alt="eoScan">
      </div>
    </div>

    <hr class="featurette-divider">

{% endblock %}